# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e4acc93ea8167fec193d8e97ed9bdd8a2ab0b4d31d9534e828f88ce15feea0877ea442d24ec6791c397d3bb70ba78819d5d639782865ffbd33f956ed76410ce

test:
  secret_key_base: 66392aa69fa35d8eca9d5131209d7fd44cf779ae079941e9614ba03269792c65e8d64fc1428b9fd440e7db417caa61662dc62c55fe421b3a3e5410126c511ba5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
